/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airom;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Rishabh sharma
 */
public class Cancel extends javax.swing.JFrame {

    /**
     * Creates new form Cancel
     */
    float ticketno;
    public Cancel() {
        initComponents();
        pnldone.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldone = new javax.swing.JPanel();
        txtdepartdate = new javax.swing.JLabel();
        txtdeparture = new javax.swing.JLabel();
        txtdestination = new javax.swing.JLabel();
        txtdepttime = new javax.swing.JLabel();
        txtarrivaltime = new javax.swing.JLabel();
        txtclass = new javax.swing.JLabel();
        txtpancard = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        txtcontact = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        btndone = new javax.swing.JButton();
        txtfliteno = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblflite2 = new javax.swing.JLabel();
        txtticketno = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cancel Ticket");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnldone.setBackground(new java.awt.Color(102, 204, 255));

        txtdepartdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdepartdate.setForeground(new java.awt.Color(255, 51, 51));
        txtdepartdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtdeparture.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdeparture.setForeground(new java.awt.Color(255, 0, 0));
        txtdeparture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtdestination.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdestination.setForeground(new java.awt.Color(255, 51, 0));
        txtdestination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtdepttime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdepttime.setForeground(new java.awt.Color(255, 0, 0));
        txtdepttime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtarrivaltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtarrivaltime.setForeground(new java.awt.Color(255, 0, 0));
        txtarrivaltime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtclass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtclass.setForeground(new java.awt.Color(255, 0, 0));
        txtclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtpancard.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtpancard.setForeground(new java.awt.Color(255, 0, 0));
        txtpancard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(255, 0, 0));
        txtfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtlastname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(255, 0, 0));
        txtlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtcontact.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(255, 0, 0));
        txtcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        btndone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndone.setText("Done");
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });

        txtfliteno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtfliteno.setForeground(new java.awt.Color(255, 0, 0));
        txtfliteno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 0, 0));
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnldoneLayout = new javax.swing.GroupLayout(pnldone);
        pnldone.setLayout(pnldoneLayout);
        pnldoneLayout.setHorizontalGroup(
            pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldoneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdepartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdepttime, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpancard, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldoneLayout.createSequentialGroup()
                        .addComponent(txtdeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnldoneLayout.createSequentialGroup()
                        .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndone, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtarrivaltime, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfliteno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );
        pnldoneLayout.setVerticalGroup(
            pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldoneLayout.createSequentialGroup()
                .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldoneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdepartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnldoneLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtfliteno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(txtdeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdepttime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(txtarrivaltime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpancard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldoneLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btndone, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldoneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnldoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldoneLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldoneLayout.createSequentialGroup()
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        getContentPane().add(pnldone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 950, 450));

        btnhome.setBackground(new java.awt.Color(0, 0, 0));
        btnhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancelation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        lblflite2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblflite2.setText("Ticket no");

        txtticketno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtticketnoActionPerformed(evt);
            }
        });
        txtticketno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtticketnoKeyReleased(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btncancel.setText("Cancel Ticket");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblflite2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtticketno, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblflite2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtticketno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 520, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 710));

        setSize(new java.awt.Dimension(981, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        ticketno = Float.parseFloat(txtticketno.getText());
        
        
        try {
            Connection con = ConnectionHelper.getCon();
            PreparedStatement pst = con.prepareStatement("Select * from customer_details where Ticketno = ?");
            pst.setFloat(1, ticketno);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                String Fliteno = rs.getString("Flite_no");
                 String Departure = rs.getString("Departure");
                String Destination = rs.getString("Destination");
                DateFormat date1 = new SimpleDateFormat("yyyy-MM-dd");
                String date = rs.getString("Departure_date");
            
                String Arrvltime = rs.getString("Arrival_time");
                 String Depttime = rs.getString("Depart_time");
                 String Class = rs.getString("Class");
                 String fname = rs.getString("Firstname");
                 String lname = rs.getString("Lastname");
                 String email = rs.getString("Email");
                 String contact = rs.getString("Contactno");
                 String address = rs.getString("Address");
                 String pancard = rs.getString("Pancard");
                 
                 txtfliteno.setText(Fliteno);
                 txtdepartdate.setText(date);
                 txtdeparture.setText(Departure);
                 txtdepttime.setText(Depttime);
                 txtarrivaltime.setText(Arrvltime);
                 txtclass.setText(Class);
                 txtfirstname.setText(fname);
                 txtlastname.setText(lname);
                 txtemail.setText(email);
                 txtcontact.setText(contact);
                 txtaddress.setText(address);
                 txtpancard.setText(pancard);
                 pnldone.setVisible(true);
            }
            else
            {
                 javax.swing.JOptionPane.showMessageDialog(this, "Wrong Ticket Number");
                txtticketno.setText("");
                txtticketno.grabFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cancel.class.getName()).log(Level.SEVERE, null, ex);
        }
        

       
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
       
        try {
             Connection con = ConnectionHelper.getCon();
            PreparedStatement pst = con.prepareStatement("DELETE FROM customer_details WHERE Ticketno = "+ticketno+"");
            pst.executeQuery();
            
        } catch (SQLException ex) {
            Logger.getLogger(Cancel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndoneActionPerformed

    private void txtticketnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtticketnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtticketnoActionPerformed

    private void txtticketnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtticketnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtticketnoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndone;
    private javax.swing.JButton btnhome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblflite2;
    private javax.swing.JPanel pnldone;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JLabel txtarrivaltime;
    private javax.swing.JLabel txtclass;
    private javax.swing.JLabel txtcontact;
    private javax.swing.JLabel txtdepartdate;
    private javax.swing.JLabel txtdeparture;
    private javax.swing.JLabel txtdepttime;
    private javax.swing.JLabel txtdestination;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtfliteno;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtpancard;
    private javax.swing.JTextField txtticketno;
    // End of variables declaration//GEN-END:variables
}
