/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airom;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rishabh sharma
 */
public class MyticketDetails extends javax.swing.JFrame {

    /**
     * Creates new form Paymentvisa
     */
    public MyticketDetails() {
        initComponents();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtpancard = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtclass = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdepttime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtarrivaltime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdepartdate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfliteno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdestination = new javax.swing.JLabel();
        txtdeparture = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtticketno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 230, -1));

        txtpancard.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtpancard.setForeground(new java.awt.Color(255, 0, 0));
        txtpancard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtpancard, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 220, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Pan-Card");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 140, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 130, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, 20));

        txtcontact.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(255, 0, 0));
        txtcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 220, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contact no");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 130, 40));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 0, 0));
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 220, 30));

        txtlastname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(255, 0, 0));
        txtlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Last name ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, 30));

        txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(255, 0, 0));
        txtfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("First name ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, 30));

        txtclass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtclass.setForeground(new java.awt.Color(255, 0, 0));
        txtclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Class");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 80, 30));

        txtdepttime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdepttime.setForeground(new java.awt.Color(255, 0, 0));
        txtdepttime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtdepttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Arrival Time ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        txtarrivaltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtarrivaltime.setForeground(new java.awt.Color(255, 0, 0));
        txtarrivaltime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtarrivaltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Departure Time ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, -1));

        txtdepartdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdepartdate.setForeground(new java.awt.Color(255, 51, 51));
        txtdepartdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtdepartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Departure Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 190, 30));

        txtfliteno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfliteno.setForeground(new java.awt.Color(153, 153, 153));
        txtfliteno.setText("Enter Your Flite No");
        txtfliteno.setCaretColor(new java.awt.Color(204, 204, 204));
        txtfliteno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtflitenoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtflitenoFocusLost(evt);
            }
        });
        txtfliteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtflitenoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfliteno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 280, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 100, 30));

        txtdestination.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdestination.setForeground(new java.awt.Color(255, 51, 0));
        txtdestination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 220, 30));

        txtdeparture.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdeparture.setForeground(new java.awt.Color(255, 0, 0));
        txtdeparture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtdeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destination");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        txtticketno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtticketno.setForeground(new java.awt.Color(255, 0, 0));
        txtticketno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtticketno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ticket no");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flite no ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airom/paymentvuisa.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtflitenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtflitenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtflitenoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fliteno = txtfliteno.getText();
            
        try {
            Connection con = ConnectionHelper.getCon();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM "+ "customer_details"+ " NATURAL JOIN "+ "searchflites");
            ResultSet rs = pst.executeQuery();
            System.out.println(rs.next()+"\n"+rs.getString("Firstname")+"\n"+rs.getString("Departure"));
            txtticketno.setText(rs.getString("Ticketno"));
            txtdepartdate.setText(rs.getString("Departure_date"));
            txtdeparture.setText(rs.getString("Departure"));
            txtdestination.setText(rs.getString("Destination"));
            txtdepttime.setText(rs.getString("Depart_time"));
            txtarrivaltime.setText(rs.getString("Arrival_time"));
            txtclass.setText(rs.getString("Class"));
               txtpancard.setText(rs.getString("Pancard"));
               txtfirstname.setText(rs.getString("Firstname"));
               txtlastname.setText(rs.getString("Lastname"));
               txtemail.setText(rs.getString("Email"));
               txtcontact.setText(rs.getString("Contactno"));
//            Connection con =ConnectionHelper.getCon();
//            PreparedStatement pst = con.prepareStatement("Select    Departure_date s2,Departure s2,Destination s2,Depart_time s2,Arrival_time s2,Class s1,Pancard s1,Firstname s1 ,Lastname s1,Email s1,Contactno s1,Address  s1 from searchflites s1,flites.customer_details s2 where Flite_no = "+fliteno+"");
//             
//            ResultSet rs =  pst.executeQuery();
//            if(rs.next())
//            {
////                
////                String ticketno = rs.getString("Ticketno");
//                DateFormat date1 = new SimpleDateFormat("yyyy-MM-dd");
//                String date = rs.getString("Departure_date");
//                String departure = rs.getString("Departure");
//                String destination = rs.getString("Destination");               
//                String departtime = rs.getString("Depart_time");
//                String arrivaltime = rs.getString("Arrival_time");
//                String Class = rs.getString("Class");
//                String pancard = rs.getString("Pancard");
//                String firstname = rs.getString("Firstname");
//                String lastname = rs.getString("Lastname");
//                String email  = rs.getString("Email");
//                String contact = rs.getString("Contactno");
//                
////                txtticketno.setText(ticketno);
//               txtdepartdate.setText(date);
//               txtdeparture.setText(departure);
//               txtdestination.setText(destination);
//               txtdepttime.setText(departtime);
//               txtarrivaltime.setText(arrivaltime);
//               txtclass.setText(Class);
//               txtpancard.setText(pancard);
//               txtfirstname.setText(firstname);
//               txtlastname.setText(lastname);
//               txtemail.setText(email);
//               txtcontact.setText(contact);
//            }
//            else
//            {
//                
//               javax.swing.JOptionPane.showMessageDialog(this, "Wrong Flite Number");
//                txtfliteno.setText("");
//                txtfliteno.grabFocus();
//            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MyticketDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtflitenoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtflitenoFocusGained
        // TODO add your handling code here:
        if(txtfliteno.getText().equals("Enter Your Flite No")){
            txtfliteno.setText("");
            txtfliteno.setForeground(new Color(0,0,0));
        }
        
        
    }//GEN-LAST:event_txtflitenoFocusGained

    private void txtflitenoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtflitenoFocusLost
        // TODO add your handling code here:
        if(txtfliteno.getText().equals("")){
            txtfliteno.setText("Enter Your Flite No");
            txtfliteno.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_txtflitenoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyticketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyticketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyticketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyticketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyticketDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JLabel txtarrivaltime;
    private javax.swing.JLabel txtclass;
    private javax.swing.JLabel txtcontact;
    private javax.swing.JLabel txtdepartdate;
    private javax.swing.JLabel txtdeparture;
    private javax.swing.JLabel txtdepttime;
    private javax.swing.JLabel txtdestination;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JTextField txtfliteno;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtpancard;
    private javax.swing.JLabel txtticketno;
    // End of variables declaration//GEN-END:variables
}
