   /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airom;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
/**
 *
 * @author Rishabh sharma
 */
public class Personalinfo extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    private UserDetails details;
    
    public Personalinfo() {
        initComponents();
       
        
        
    }
     public Personalinfo(UserDetails userDetails) {
        initComponents();
        this.details = userDetails;
     txtfliteno.setText(String.valueOf(userDetails.Fliteno));
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfliteno = new javax.swing.JLabel();
        txtpancard = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnprv = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfliteno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtfliteno.setForeground(new java.awt.Color(0, 0, 255));
        txtfliteno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtfliteno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 220, 50));
        getContentPane().add(txtpancard, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 240, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Pan-Card");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 80, 30));

        btnhome.setBackground(new java.awt.Color(0, 0, 0));
        btnhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 30));

        btnprv.setBackground(new java.awt.Color(0, 0, 0));
        btnprv.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnprv.setForeground(new java.awt.Color(255, 255, 255));
        btnprv.setText("<<");
        btnprv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprvActionPerformed(evt);
            }
        });
        getContentPane().add(btnprv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        btnpayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpayment.setForeground(new java.awt.Color(255, 0, 0));
        btnpayment.setText("PAYMENT");
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 120, 30));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Address :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 70, 20));
        getContentPane().add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 240, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Contact no:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 240, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("@e_mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, 20));

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Last name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, 20));

        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("First name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 609, 674));

        setSize(new java.awt.Dimension(623, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed

         UserDetails details1 = new UserDetails();
        
  details1.fname =txtfname.getText();
    details1.lname =txtlname.getText();
   details1.email = txtemail.getText();
    details1.contactno = Long.parseLong(txtcontact.getText());
     details1.address = txtaddress.getText();
    details1.pancard = Long.parseLong(txtpancard.getText());  
    
     
    
        try {
            int ticketNo =  ConnectionHelper.getTickeNo();
              Connection con = ConnectionHelper.getCon();
              
              PreparedStatement pst = con.prepareStatement("Insert into customer_details(Ticketno,Flite_no,Class,Firstname,Lastname,Email,Contactno,Address,Pancard) values (?,?,?,?,?,?,?,?,?)");
             pst.setLong(1, ticketNo);
             pst.setLong(2, details.Fliteno);
             pst.setString(3, details.Class);
             pst.setString(4, details1.fname);
             pst.setString(5, details1.lname);
             pst.setString(6, details1.email);
             pst.setLong(7, details1.contactno);
             pst.setString(8, details1.address);
             pst.setLong(9, details1.pancard);
             
              pst.execute();
              con.close();

         new Payment().setVisible(true);
        this.dispose(); 
        } catch (SQLException ex) {
            Logger.getLogger(Personalinfo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Not Running");
        }
   
        
        
    }//GEN-LAST:event_btnpaymentActionPerformed

    private void btnprvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprvActionPerformed
Booking bk = new Booking();
bk.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnprvActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
Home hm = new Home();
hm.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void txtfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyReleased
    }//GEN-LAST:event_txtfnameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnprv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtfliteno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtpancard;
    // End of variables declaration//GEN-END:variables
}
