/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airom;


import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishabh sharma
 */
public class Searching extends javax.swing.JFrame {

    private Vector<?> row;

    /**
     * Creates new form Searching
     */
    public Searching() {
        initComponents();
        
                
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dt = new javax.swing.JTextField();
        txtto = new javax.swing.JComboBox<>();
        txtfrom = new javax.swing.JComboBox<>();
        btnhome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttable = new javax.swing.JTable();
        btnsearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblbg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 270, 40));

        txtto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Goa", "Chennai", "Hydrabad", "Kolkata", "Delhi", "Chandigarh", "Gujarat", "Kerela", "AandraPradesh", "Haryana", "Rajasthan", "Sikkim", " " }));
        getContentPane().add(txtto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 270, 40));

        txtfrom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Mumbai", "Goa", "Hydrabad", "Kolkata", "Assam", "MadhayaPradesh", "Bihar", "Maharashtra", "Punjab", "Uttarakhand" }));
        txtfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfromActionPerformed(evt);
            }
        });
        getContentPane().add(txtfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 270, 40));

        btnhome.setBackground(new java.awt.Color(0, 0, 0));
        btnhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        txttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(txttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 870, 260));

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 0, 0));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Depart:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("FROM:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("      Searching Flites....");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 480, 40));

        lblbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Searchbg.jpg"))); // NOI18N
        getContentPane().add(lblbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 100, -1));

        setSize(new java.awt.Dimension(883, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
String from = txtfrom.getSelectedItem().toString();
String to = txtto.getSelectedItem().toString();

DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
String date = dt.getText();


try{
Connection con = ConnectionHelper.getCon();
System.err.print(date);
String query = "Select * from searchflites where Departure LIKE  '%"+from+"%' And Destination Like '%"+to+"%' And Departure_date = '"+date+"'";
PreparedStatement pst = con.prepareStatement(query);
ResultSet rs = pst.executeQuery();

ResultSetMetaData rsmd = rs.getMetaData();
    DefaultTableModel model = (DefaultTableModel)txttable.getModel();
    
    int colms = rsmd.getColumnCount();
    String[] colName = new String[colms];
    for(int i=0; i<colms; i++)
    {
        colName[i] = rsmd.getColumnName(i+1);
        model.setColumnIdentifiers(colName);
    }
    
    String Flite_no,Flite_name,From,To,Departure_date,Dept_time,Arrival_time,Available_seat,Economy,Business;
     while(rs.next())
        {
            Flite_no = rs.getString(1);
            Flite_name = rs.getString(2);
            From = rs.getString(3);
            To = rs.getString(4);
            Departure_date = rs.getString(5);
            Dept_time = rs.getString(6);
            Arrival_time = rs.getString(7);
            Available_seat = rs.getString(8);
            Economy = rs.getString(9);
            Business = rs.getString(10);
           
            String[] row = {Flite_no,Flite_name,From,To,Departure_date,Dept_time,Arrival_time,Available_seat,Economy,Business};
            model.addRow(row);           
        }  
    
     pst.close();
     con.close();
            
}
catch(Exception e){
    
    e.printStackTrace();
}
        
        
     
    }//GEN-LAST:event_btnsearchActionPerformed
    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
      Home hm = new Home();
      hm.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void txtfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfromActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTextField dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbg;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JTable txttable;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
